// Interop tests: the Dart crypto and URL parsing must interoperate with the
// desktop's wire protocol. The fixtures in test/fixtures/interop.json were
// generated by tool/gen-interop-vectors.mjs using the exact WebCrypto calls
// of src/mobile/crypto.ts — the code that already interops with the desktop.
//
// Regenerate the fixture with: node tool/gen-interop-vectors.mjs
// (fixture is committed; the regeneration only refreshes the sealed frames'
// random nonces — proof and key are deterministic and must never change).

import 'dart:convert';
import 'dart:io';

import 'package:cryptography/cryptography.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:grasberg_mobile/models/models.dart';
import 'package:grasberg_mobile/protocol/crypto.dart';
import 'package:grasberg_mobile/protocol/urls.dart';
import 'package:grasberg_mobile/state/identity.dart';

void main() {
  final fixturePath = '${Directory.current.path}/test/fixtures/interop.json';
  final fixture = jsonDecode(File(fixturePath).readAsStringSync()) as Map<String, dynamic>;
  final secret = fixture['secret'] as String;
  final frames = fixture['sealedFrames'] as Map<String, dynamic>;
  final expected = fixture['expected'] as Map<String, dynamic>;

  group('pairing proof (HMAC-SHA256, hex)', () {
    test('matches the desktop/webcrypto vector', () async {
      final proof = await pairingProof(secret);
      expect(proof, fixture['proofHex']);
    });
  });

  group('frame key (HKDF-SHA256 → 256-bit)', () {
    test('matches the desktop/webcrypto vector', () async {
      final key = await deriveFrameKey(secret);
      expect(base64Encode(key), fixture['frameKeyBase64']);
    });

    test('is stable across derivations', () async {
      final a = await deriveFrameKey(secret);
      final b = await deriveFrameKey(secret);
      expect(a, b);
    });
  });

  group('openFrame (WebCrypto-sealed input)', () {
    late SecretKey key;

    setUpAll(() async {
      key = SecretKey(keyFromBase64(fixture['frameKeyBase64'] as String));
    });

    test('opens the inner hello', () async {
      final opened = await openFrame(key, Map<String, dynamic>.from(frames['hello']));
      expect(opened, {'t': 'hello'});
    });

    test('opens the paired reply with identity fields', () async {
      final opened = await openFrame(key, Map<String, dynamic>.from(frames['paired']));
      expect(opened, isA<Map>());
      final m = opened! as Map;
      expect(m['t'], 'paired');
      expect(m['deviceId'], expected['deviceId']);
      expect(m['token'], 'relay-token-abc123');
      expect(m['desktopName'], 'Test Desktop');
    });

    test('opens a tunneled IPC request (channel/seq/args intact)', () async {
      final opened = await openFrame(key, Map<String, dynamic>.from(frames['req']));
      final m = opened! as Map;
      expect(m['t'], 'req');
      expect(m['id'], 'req-0001');
      expect(m['seq'], 1);
      expect(m['channel'], 'conv:list');
      expect(m['args'], [{}]);
    });

    test('opens a push frame', () async {
      final opened = await openFrame(key, Map<String, dynamic>.from(frames['push']));
      final m = opened! as Map;
      expect(m['t'], 'push');
      expect(m['channel'], 'push:conversationsChanged');
      expect(m['payload'], {'conversationId': 'conv-1'});
    });

    test('rejects tampered ciphertext', () async {
      final tampered = Map<String, dynamic>.from(frames['hello']);
      final ct = base64Decode(tampered['ct'] as String);
      ct[0] = ct[0] ^ 0xff;
      tampered['ct'] = base64Encode(ct);
      expect(() => openFrame(key, tampered), throwsA(anything));
    });

    test('rejects a wrong key', () async {
      final wrong = SecretKey(await deriveFrameKey('$secret-wrong'));
      // 50-char secret is not a valid pairing secret but still derivable;
      // the point is: different key ⇒ GCM tag check fails.
      expect(() => openFrame(wrong, Map<String, dynamic>.from(frames['hello'])),
          throwsA(anything));
    });
  });

  group('sealFrame (Dart output shape)', () {
    test('produces {t:sec, n, ct} with a 16-byte tag appended', () async {
      final key = SecretKey(keyFromBase64(fixture['frameKeyBase64'] as String));
      final payload = {'t': 'hello'};
      final sealed = await sealFrame(key, payload);
      expect(sealed['t'], 'sec');
      expect(base64Decode(sealed['n'] as String).length, 12);
      // 13 bytes of JSON ({"t":"hello"}) + 16-byte GCM tag, base64-encoded.
      final ct = base64Decode(sealed['ct'] as String);
      expect(ct.length, 13 + 16);
      final opened = await openFrame(key, sealed);
      expect(opened, payload);
    });

    test('uses fresh nonces per seal', () async {
      final key = SecretKey(keyFromBase64(fixture['frameKeyBase64'] as String));
      final a = await sealFrame(key, {'n': 1});
      final b = await sealFrame(key, {'n': 1});
      expect(a['n'], isNot(b['n']));
    });
  });

  group('relayWsUrl', () {
    test('normalizes https to wss and pins the /ws path', () {
      expect(relayWsUrl('https://relay.example.com:7333'), 'wss://relay.example.com:7333/ws');
      expect(relayWsUrl('wss://relay.example.com'), 'wss://relay.example.com/ws');
      expect(relayWsUrl('wss://relay.example.com/ws'), 'wss://relay.example.com/ws');
    });

    test('strips query and fragment', () {
      expect(relayWsUrl('wss://relay.example.com/ws?x=1#frag'), 'wss://relay.example.com/ws');
    });

    test('plain ws only for loopback', () {
      expect(relayWsUrl('http://127.0.0.1:7333'), 'ws://127.0.0.1:7333/ws');
      expect(relayWsUrl('http://localhost:7333'), 'ws://localhost:7333/ws');
      expect(relayWsUrl('http://relay.example.com'), isNull);
      expect(relayWsUrl('ws://relay.example.com'), isNull);
    });

    test('rejects garbage', () {
      expect(relayWsUrl('not a url'), isNull);
      expect(relayWsUrl('ftp://relay.example.com'), isNull);
      expect(relayWsUrl(''), isNull);
    });
  });

  group('pairing QR parsing', () {
    test('parses the desktop-built QR payload', () {
      final qr = parsePairingQr(fixture['pairingQr'] as String);
      expect(qr, isNotNull);
      expect(qr!.secret, secret);
      expect(qr.desktopId, expected['desktopId']);
      expect(qr.relayUrl, expected['relayUrl']);
    });

    test('rejects a wrong-length secret', () {
      final text = 'https://phone.example/app#p=short&relay=https://r.example&desktop=abc';
      expect(parsePairingQr(text), isNull);
    });

    test('rejects missing fields', () {
      expect(parsePairingQr('https://phone.example/app#p=${'x' * 43}'), isNull);
      expect(parsePairingQr('https://phone.example/app'), isNull);
      expect(parsePairingQr('random text'), isNull);
    });
  });

  group('Identity persistence', () {
    test('JSON round-trip', () {
      final identity = Identity(
        relayUrl: 'https://relay.example.com',
        desktopId: 'desktop-1',
        deviceId: 'device-1',
        token: 'token-1',
        keyBase64: fixture['frameKeyBase64'] as String,
        nextRequestSeq: 7,
      );
      final parsed = Identity.fromJson(jsonDecode(jsonEncode(identity.toJson())));
      expect(parsed, isNotNull);
      expect(parsed!.nextRequestSeq, 7);
      expect(parsed.deviceId, 'device-1');
      expect(parsed.keyBase64, fixture['frameKeyBase64']);
    });

    test('rejects incomplete identities', () {
      expect(Identity.fromJson({'relayUrl': 'wss://x/ws'}), isNull);
      expect(Identity.fromJson({
        'relayUrl': 'not a url',
        'desktopId': 'd',
        'deviceId': 'v',
        'token': 't',
        'keyBase64': 'k',
      }), isNull);
    });

    test('clamps the request sequence', () {
      final identity = Identity(
        relayUrl: 'https://relay.example.com',
        desktopId: 'd',
        deviceId: 'v',
        token: 't',
        keyBase64: 'AAAA',
        nextRequestSeq: -3,
      );
      expect(identity.nextRequestSeq, 1);
    });
  });

  group('model parsing (desktop JSON payloads)', () {
    test('parses an assistant message with tool calls', () {
      final message = Message.fromJson({
        'id': 'm1',
        'conversationId': 'c1',
        'role': 'assistant',
        'content': '# Hello',
        'reasoning': 'thinking…',
        'status': 'complete',
        'seq': 3,
        'createdAt': 1700000000000,
        'modelId': 'gpt-test',
        'toolCalls': [
          {'id': 'tc1', 'name': 'fetch_url', 'arguments': '{"url":"https://x"}', 'status': 'done'},
        ],
        'unknownFutureField': {'ignored': true},
      });
      expect(message.role, 'assistant');
      expect(message.reasoning, 'thinking…');
      expect(message.toolCalls.single.name, 'fetch_url');
      expect(message.modelId, 'gpt-test');
    });

    test('parses stream envelopes of every shape the phone acts on', () {
      final text = StreamEventEnvelope.fromJson({
        'streamId': 's1',
        'conversationId': 'c1',
        'event': {'type': 'text-delta', 'text': 'Hej'},
      });
      expect(text.isDelta, isTrue);
      expect(text.text, 'Hej');

      final failover = StreamEventEnvelope.fromJson({
        'streamId': 's1',
        'conversationId': 'c1',
        'event': {'type': 'failover', 'message': {'id': 'm2'}},
      });
      expect(failover.type, 'failover');
      expect(failover.message!.id, 'm2');

      final done = StreamEventEnvelope.fromJson({
        'streamId': 's1',
        'conversationId': 'c1',
        'event': {
          'type': 'done',
          'finishReason': 'stop',
          'message': {
            'id': 'm2',
            'conversationId': 'c1',
            'role': 'assistant',
            'content': 'Färdig',
            'status': 'complete',
            'seq': 4,
            'createdAt': 1700000000001,
          },
        },
      });
      expect(done.isTerminal, isTrue);
      expect(done.message!.content, 'Färdig');

      final error = StreamEventEnvelope.fromJson({
        'streamId': 's1',
        'conversationId': 'c1',
        'event': {
          'type': 'error',
          'error': {'code': 'timeout', 'message': 'Timed out', 'retryable': true},
          'message': {'id': 'm2'},
        },
      });
      expect(error.errorMessage, 'Timed out');
    });

    test('parses approval and question requests', () {
      final approval = ToolApprovalRequest.fromJson({
        'requestId': 'r1',
        'streamId': 's1',
        'conversationId': 'c1',
        'toolCall': {'name': 'run_shell_command', 'arguments': '{"command":"ls"}'},
        'risk': 'high',
        'note': 'Runs in the workspace folder',
      });
      expect(approval.toolName, 'run_shell_command');
      expect(approval.risk, 'high');
      expect(approval.note, 'Runs in the workspace folder');

      final question = UserQuestionRequest.fromJson({
        'requestId': 'r2',
        'streamId': 's1',
        'conversationId': 'c1',
        'question': 'Which one?',
        'options': ['A', 'B'],
      });
      expect(question.options, ['A', 'B']);
    });

    test('IpcResult success and failure', () {
      final ok = IpcResult<List<Object?>>.ok([{'id': 'c1'}]);
      expect(ok.ok, isTrue);
      expect(ok.data!.first, isA<Map>());

      final err = IpcResult<int>.err(IpcError.fromJson({
        'code': 'timeout',
        'message': 'Too slow',
        'retryable': true,
      }));
      expect(err.ok, isFalse);
      expect(err.error!.code, 'timeout');
      expect(err.error!.retryable, isTrue);
    });
  });

  group('uuid', () {
    test('is a valid v4 uuid', () {
      final uuid = randomUuid();
      expect(
        RegExp(r'^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$')
            .hasMatch(uuid),
        isTrue,
        reason: 'got $uuid',
      );
    });
  });
}
