/**
 * Provider config CRUD + encrypted-key row access.
 *
 * The `provider_keys` table only ever stores the safeStorage-encrypted key
 * (base64) and a masked preview. The full key never leaves the main process;
 * this repository never logs or returns it except via `getEncryptedKey`,
 * whose callers must decrypt in-memory only.
 */

import type {
  ProviderConfig,
  ProviderConfigInput,
  ProviderConfigPatch,
  ProviderType,
} from '@shared/types'
import type { SqliteDriver, SqlValue } from '../driver'

/** Caller resolves id/baseUrl/defaultModelId (catalog defaults) before insert. */
export type ProviderCreateInput = ProviderConfigInput & {
  id: string
  baseUrl: string
  defaultModelId: string
}

export interface ProvidersRepository {
  list(): ProviderConfig[]
  getById(id: string): ProviderConfig | null
  /** Id is generated by the caller (crypto.randomUUID). */
  create(input: ProviderCreateInput): ProviderConfig
  /** Returns the updated row, or null when the id is unknown. */
  update(id: string, patch: ProviderConfigPatch): ProviderConfig | null
  remove(id: string): void
  setKeyRow(providerId: string, encryptedKeyBase64: string, keyPreview: string): void
  deleteKeyRow(providerId: string): void
  getEncryptedKey(providerId: string): string | null
}

interface ProviderRow {
  id: string
  type: string
  label: string
  base_url: string
  default_model_id: string
  enabled: number
  created_at: number
  updated_at: number
  key_preview: string | null
}

const SELECT_PROVIDER = `
  SELECT p.id, p.type, p.label, p.base_url, p.default_model_id, p.enabled,
         p.created_at, p.updated_at, k.key_preview
  FROM providers p
  LEFT JOIN provider_keys k ON k.provider_id = p.id
`

function toProviderConfig(row: ProviderRow): ProviderConfig {
  return {
    id: row.id,
    type: row.type as ProviderType,
    label: row.label,
    baseUrl: row.base_url,
    defaultModelId: row.default_model_id,
    enabled: row.enabled !== 0,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    hasKey: row.key_preview !== null,
    keyPreview: row.key_preview,
  }
}

export function createProvidersRepository(driver: SqliteDriver): ProvidersRepository {
  const getById = (id: string): ProviderConfig | null => {
    const row = driver.get<ProviderRow>(`${SELECT_PROVIDER} WHERE p.id = ?`, [id])
    return row ? toProviderConfig(row) : null
  }

  return {
    list() {
      const rows = driver.all<ProviderRow>(`${SELECT_PROVIDER} ORDER BY p.created_at ASC`)
      return rows.map(toProviderConfig)
    },

    getById,

    create(input) {
      const now = Date.now()
      driver.run(
        `INSERT INTO providers
           (id, type, label, base_url, default_model_id, enabled, created_at, updated_at)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
        [
          input.id,
          input.type,
          input.label,
          input.baseUrl,
          input.defaultModelId,
          input.enabled === false ? 0 : 1,
          now,
          now,
        ]
      )
      const created = getById(input.id)
      if (!created) throw new Error('Failed to read back created provider')
      return created
    },

    update(id, patch) {
      const sets: string[] = []
      const params: SqlValue[] = []
      if (patch.label !== undefined) {
        sets.push('label = ?')
        params.push(patch.label)
      }
      if (patch.baseUrl !== undefined) {
        sets.push('base_url = ?')
        params.push(patch.baseUrl)
      }
      if (patch.defaultModelId !== undefined) {
        sets.push('default_model_id = ?')
        params.push(patch.defaultModelId)
      }
      if (patch.enabled !== undefined) {
        sets.push('enabled = ?')
        params.push(patch.enabled ? 1 : 0)
      }
      if (sets.length > 0) {
        sets.push('updated_at = ?')
        params.push(Date.now(), id)
        driver.run(`UPDATE providers SET ${sets.join(', ')} WHERE id = ?`, params)
      }
      return getById(id)
    },

    remove(id) {
      // provider_keys row cascades via FK.
      driver.run('DELETE FROM providers WHERE id = ?', [id])
    },

    setKeyRow(providerId, encryptedKeyBase64, keyPreview) {
      driver.run(
        `INSERT INTO provider_keys (provider_id, encrypted_key, key_preview, updated_at)
         VALUES (?, ?, ?, ?)
         ON CONFLICT(provider_id) DO UPDATE SET
           encrypted_key = excluded.encrypted_key,
           key_preview = excluded.key_preview,
           updated_at = excluded.updated_at`,
        [providerId, encryptedKeyBase64, keyPreview, Date.now()]
      )
    },

    deleteKeyRow(providerId) {
      driver.run('DELETE FROM provider_keys WHERE provider_id = ?', [providerId])
    },

    getEncryptedKey(providerId) {
      const row = driver.get<{ encrypted_key: string }>(
        'SELECT encrypted_key FROM provider_keys WHERE provider_id = ?',
        [providerId]
      )
      return row ? row.encrypted_key : null
    },
  }
}
