/**
 * Provider config CRUD + encrypted-key row access.
 *
 * The `provider_keys` table only ever stores the safeStorage-encrypted key
 * (base64) and a masked preview. The full key never leaves the main process;
 * this repository never logs or returns it except via `getEncryptedKey`,
 * whose callers must decrypt in-memory only.
 */

import type {
  AuthMode,
  ProviderConfig,
  ProviderConfigInput,
  ProviderConfigPatch,
  ProviderType,
} from '@shared/types'
import type { SqliteDriver, SqlValue } from '../driver'

/** Caller resolves id/baseUrl/defaultModelId (catalog defaults) before insert. */
export type ProviderCreateInput = ProviderConfigInput & {
  id: string
  baseUrl: string
  defaultModelId: string
}

/**
 * Encrypted OAuth token material for a provider (safeStorage ciphertext,
 * base64). Plaintext tokens never touch this shape or the DB.
 */
export interface OAuthTokenRow {
  providerId: string
  encryptedAccess: string
  encryptedRefresh: string | null
  accountId: string | null
  accountLabel: string | null
  expiresAt: number | null
}

export interface ProvidersRepository {
  list(): ProviderConfig[]
  getById(id: string): ProviderConfig | null
  /** Id is generated by the caller (crypto.randomUUID). */
  create(input: ProviderCreateInput): ProviderConfig
  /** Returns the updated row, or null when the id is unknown. */
  update(id: string, patch: ProviderConfigPatch): ProviderConfig | null
  remove(id: string): void
  setKeyRow(providerId: string, encryptedKeyBase64: string, keyPreview: string): void
  deleteKeyRow(providerId: string): void
  getEncryptedKey(providerId: string): string | null
  /** OAuth session storage (encrypted tokens only). */
  setOAuthRow(row: OAuthTokenRow): void
  getOAuthRow(providerId: string): OAuthTokenRow | null
  deleteOAuthRow(providerId: string): void
}

interface ProviderRow {
  id: string
  type: string
  label: string
  base_url: string
  default_model_id: string
  enabled: number
  auth_mode: string
  preset_id: string | null
  created_at: number
  updated_at: number
  key_preview: string | null
  oauth_account_label: string | null
  oauth_present: number | null
}

const SELECT_PROVIDER = `
  SELECT p.id, p.type, p.label, p.base_url, p.default_model_id, p.enabled,
         p.auth_mode, p.preset_id, p.created_at, p.updated_at, k.key_preview,
         o.account_label AS oauth_account_label,
         o.provider_id AS oauth_present
  FROM providers p
  LEFT JOIN provider_keys k ON k.provider_id = p.id
  LEFT JOIN provider_oauth o ON o.provider_id = p.id
`

function toProviderConfig(row: ProviderRow): ProviderConfig {
  return {
    id: row.id,
    type: row.type as ProviderType,
    label: row.label,
    baseUrl: row.base_url,
    defaultModelId: row.default_model_id,
    enabled: row.enabled !== 0,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    authMode: (row.auth_mode as AuthMode) ?? 'api_key',
    presetId: row.preset_id,
    hasKey: row.key_preview !== null,
    keyPreview: row.key_preview,
    oauthConnected: row.oauth_present !== null,
    oauthAccountLabel: row.oauth_account_label,
  }
}

export function createProvidersRepository(driver: SqliteDriver): ProvidersRepository {
  const getById = (id: string): ProviderConfig | null => {
    const row = driver.get<ProviderRow>(`${SELECT_PROVIDER} WHERE p.id = ?`, [id])
    return row ? toProviderConfig(row) : null
  }

  return {
    list() {
      const rows = driver.all<ProviderRow>(`${SELECT_PROVIDER} ORDER BY p.created_at ASC`)
      return rows.map(toProviderConfig)
    },

    getById,

    create(input) {
      const now = Date.now()
      driver.run(
        `INSERT INTO providers
           (id, type, label, base_url, default_model_id, enabled, auth_mode, preset_id, created_at, updated_at)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [
          input.id,
          input.type,
          input.label,
          input.baseUrl,
          input.defaultModelId,
          input.enabled === false ? 0 : 1,
          input.authMode ?? 'api_key',
          input.presetId ?? null,
          now,
          now,
        ]
      )
      const created = getById(input.id)
      if (!created) throw new Error('Failed to read back created provider')
      return created
    },

    update(id, patch) {
      const sets: string[] = []
      const params: SqlValue[] = []
      if (patch.label !== undefined) {
        sets.push('label = ?')
        params.push(patch.label)
      }
      if (patch.baseUrl !== undefined) {
        sets.push('base_url = ?')
        params.push(patch.baseUrl)
      }
      if (patch.defaultModelId !== undefined) {
        sets.push('default_model_id = ?')
        params.push(patch.defaultModelId)
      }
      if (patch.enabled !== undefined) {
        sets.push('enabled = ?')
        params.push(patch.enabled ? 1 : 0)
      }
      if (sets.length > 0) {
        sets.push('updated_at = ?')
        params.push(Date.now(), id)
        driver.run(`UPDATE providers SET ${sets.join(', ')} WHERE id = ?`, params)
      }
      return getById(id)
    },

    remove(id) {
      // provider_keys row cascades via FK.
      driver.run('DELETE FROM providers WHERE id = ?', [id])
    },

    setKeyRow(providerId, encryptedKeyBase64, keyPreview) {
      driver.run(
        `INSERT INTO provider_keys (provider_id, encrypted_key, key_preview, updated_at)
         VALUES (?, ?, ?, ?)
         ON CONFLICT(provider_id) DO UPDATE SET
           encrypted_key = excluded.encrypted_key,
           key_preview = excluded.key_preview,
           updated_at = excluded.updated_at`,
        [providerId, encryptedKeyBase64, keyPreview, Date.now()]
      )
    },

    deleteKeyRow(providerId) {
      driver.run('DELETE FROM provider_keys WHERE provider_id = ?', [providerId])
    },

    getEncryptedKey(providerId) {
      const row = driver.get<{ encrypted_key: string }>(
        'SELECT encrypted_key FROM provider_keys WHERE provider_id = ?',
        [providerId]
      )
      return row ? row.encrypted_key : null
    },

    setOAuthRow(row) {
      driver.run(
        `INSERT INTO provider_oauth
           (provider_id, encrypted_access, encrypted_refresh, account_id, account_label, expires_at, updated_at)
         VALUES (?, ?, ?, ?, ?, ?, ?)
         ON CONFLICT(provider_id) DO UPDATE SET
           encrypted_access = excluded.encrypted_access,
           encrypted_refresh = excluded.encrypted_refresh,
           account_id = excluded.account_id,
           account_label = excluded.account_label,
           expires_at = excluded.expires_at,
           updated_at = excluded.updated_at`,
        [
          row.providerId,
          row.encryptedAccess,
          row.encryptedRefresh,
          row.accountId,
          row.accountLabel,
          row.expiresAt,
          Date.now(),
        ]
      )
    },

    getOAuthRow(providerId) {
      const row = driver.get<{
        encrypted_access: string
        encrypted_refresh: string | null
        account_id: string | null
        account_label: string | null
        expires_at: number | null
      }>(
        `SELECT encrypted_access, encrypted_refresh, account_id, account_label, expires_at
         FROM provider_oauth WHERE provider_id = ?`,
        [providerId]
      )
      if (!row) return null
      return {
        providerId,
        encryptedAccess: row.encrypted_access,
        encryptedRefresh: row.encrypted_refresh,
        accountId: row.account_id,
        accountLabel: row.account_label,
        expiresAt: row.expires_at,
      }
    },

    deleteOAuthRow(providerId) {
      driver.run('DELETE FROM provider_oauth WHERE provider_id = ?', [providerId])
    },
  }
}
