/**
 * Regenerates src/shared/presets.generated.ts from the models.dev catalog.
 *
 * The mapping lives in the pure, unit-tested src/shared/presets.build.ts; this
 * script only does IO. Run it (esbuild-bundled, since the repo has no tsx):
 *
 *   node_modules/.bin/esbuild scripts/generate-presets.ts --bundle \
 *     --platform=node --format=cjs --outfile=/tmp/gen.cjs
 *   node /tmp/gen.cjs [path-to-api.json]   # omit the path to fetch models.dev
 *
 * Commit the regenerated presets.generated.ts.
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { buildPresetCatalog, type ModelsDevApi } from '../src/shared/presets.build'

async function loadApi(): Promise<ModelsDevApi> {
  const path = process.argv[2]
  if (path) return JSON.parse(readFileSync(path, 'utf8')) as ModelsDevApi
  const res = await fetch('https://models.dev/api.json')
  return (await res.json()) as ModelsDevApi
}

async function main(): Promise<void> {
  const api = await loadApi()
  const { meta, models, skipped } = buildPresetCatalog(api)
  const modelCount = Object.values(models).reduce((s, m) => s + m.length, 0)
  const content =
    `/* eslint-disable */\n` +
    `// AUTO-GENERATED by scripts/generate-presets.ts from models.dev — do not edit by hand.\n` +
    `import type { PresetMeta } from './presets.build'\n\n` +
    `export const PRESET_META: PresetMeta[] = ${JSON.stringify(meta)}\n\n` +
    `export const PRESET_MODELS_JSON = ${JSON.stringify(JSON.stringify(models))}\n`
  writeFileSync('src/shared/presets.generated.ts', content)
  console.error(
    `Wrote ${meta.length} presets, ${modelCount} models to src/shared/presets.generated.ts.` +
      `\nSkipped (no base URL): ${skipped.join(', ') || 'none'}`
  )
}

void main()
